[package]
name = "torrex"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features=["derive"]}
serde_bencode = "0.2.4"
serde_bytes = "0.11.17"
serde_json = "1.0.140"
sha1 = "0.10.6"
